---
- name: Checking whether the log files are present in the Ezpay folder
  hosts: 10.10.35.127
  gather_facts: no
  tasks:
    - name: Checking Ezpay application Installed on the EFT server"
      ansible.windows.win_powershell:
        script: |
          $applicationName = "Ezpay Server"
          $installedApps = Get-WmiObject -Class Win32_Product | Select-Object -ExpandProperty Name
          return $installedApps -contains $applicationName

    - name: Checking EFT cashless server installed on the EFT Server"
      ansible.windows.win_powershell:
        script: |
          $applicationName = "EFT Cashless Server"
          $installedApps = Get-WmiObject -Class Win32_Product | Select-Object -ExpandProperty Name
          return $installedApps -contains $applicationName

    - name: checking log file
      win_find:
        paths: C:\\Program Files (x86)\\IGT Systems\\EZPay
        patterns: [ '*.log', '*.LST' ]

   # - name: Verify whether added the Client connection to Translator ip in the log file"
   #   ansible.windows.win_powershell:
    #    script: |
     #     (Get-ChildItem -Path "C:\Program Files (x86)\IGT Systems\EZPay\server\ivs_ss_server\Log" | Sort-Object LastWriteTime -Descending | Select-Object -First 1 | Get-Content -Raw | Select-String -quiet "Added client connection")

- name: verify TCKT is OK
  hosts: 10.10.35.121
  tasks:
    - name: Checking the status of  the Translator service in Translator Machine
      win_service:
        name: AbsTranslator
        state: started
