---
- name: Restarting the Translator service in Translator Machine
  hosts: STN-Trans
  tasks:
    - name: Restarting the translator service
      win_service:
        name: AbsTranslator
        state: restarted

    - name:
      debug:
        msg:
        - "The Install part of Ezpay is completed and run the Confirm-CSAEzpayInstall script to verify the completion"
