#ansible-playbook preflightfinal.yml -e "mediapath=C:/map databasename=EZPay"

---
- name: starting preflight tests
  hosts: all
  gather_facts: no
  tasks:
    - name: Checking all the machines are available to Start the Installation
      win_ping:

- name: Checking .net 3.5 feature is enabled in all machines
  hosts: all
  tasks:
    - name: Verifying in all the machines to have .net 3.5 feature enabled in server manager
      community.windows.win_feature_info:
        name: Net-Framework-Core
      register: feature_info
        
    - name: .net 3.5 feature not installed, please install and try again
      fail:
        msg: "Feature .net 3.5 is not installed. State: {{ feature_info.features[0].install_state }}"
      when: feature_info.features[0].install_state != "Installed"
      any_errors_fatal: true

- name: Checking .net 4.8 framework is installed
  hosts: all
  tasks:
    - name: Verifying in all the machines for Ezpay Install
      ansible.windows.win_reg_stat:
        path: 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full'
        name: Release
      register: net_reginfo
       
    - name: .net 4.8 framework is not installed, please install and try again.
      fail:
        msg: "Framework .net 4.8 is not installed. It should have version greater than or equal to 528040. Current Release Version: {{ net_reginfo.value }}"
      when: net_reginfo.value <= 528040
      any_errors_fatal: true

- name: Checking access to the media files
  hosts: all
  gather_facts: no
  vars:
    mediapath : "{{ mediapath  }}"
  tasks:
    - name: Should have access to the media files
      ansible.windows.win_stat:
        path: "{{ mediapath }}"

#- name: Checking if database exists
 # hosts: 10.10.35.131
  #gather_facts: no
 # vars:
  #  databasename: "{{ databasename }}"
  #tasks:
  #  - name: Should have access to '{{ databasename }}'
  #    ansible.windows.win_shell: |
   #     (Get-SqlDatabase -Name '{{ databasename }}') -ne $null

- name: Check whether EzpayReportusers group Created in Dc server
  hosts: 10.10.35.10
  gather_facts: no
  ignore_unreachable: true
  tasks:
    - name: If the EzpayReportusers group not available, it will Create now
      ansible.windows.win_group:
        name: EzPayReportUsers
        state: present
